services:
  # FastAPI Backend Service
  - type: web
    name: mli-rag-demo-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  # Streamlit Frontend Service
  - type: web
    name: mli-rag-demo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Home.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
